#!/usr/bin/perl

=pod

=head1 NAME

compat.pl - Generate compat headers from clang-tidy output

=head1 SYNOPSIS

perl compat.pl [ -G ] [ -F ] [ FILE ... ]

=head1 DESCRIPTION

Read output generated by C<clang-tidy> when running the
B<cheri-Uapi> check and process it to generate compat headers.

The warnings produced by the C<clang-tidy> check annotate existing
UAPI headers. These annotations are used to generate compat64 and
compat32 versions of these headers.

The compat version of a header file is placed into the same
directory as the original header file with C<compat64_> or C<compat32_>
prefixed to the file name. For most structures this process is able to
generate compat versions of UAPI structs and automatic conversion functions
to convert between the compat and the native version of the struct.

In a few cases the result is determined not be reliable. In particular
this is the case if the extracted compat structure contains preprocessor
conditions. In this case the affected structures are stored in a file
prefixed with C<compat64_i_> or C<compat32_i_> instead. These files must
be inspected and fixed manually.

Additionally, the script can generate global files in C<compat/> that
list all include files that had compat versions generated and a file
that contains all affected structs and their fields. This is used to
compare the layout of the generated compat structs to that of the
native structs.

Supported command line options

=over

=item -G

Regenerate the global files in C<compat/>. The default is not to regenerated them.
Only use this option if your clang-tidy output includes annotations for all uapi
header files.

=item -F

Force regeneration of the manual include files (those with the C<compat32_i_>
or C<compat64_i_> prefix. The default is to generate them only if they do
not exist. Note that you have to delete these files manually if they exist
and are no longer needed.

=back

=cut


use strict;
use warnings;
use Getopt::Std;

my @ops32 = ();
my @ops64 = ();
my %opts;

die "Invalid option" unless getopts('GF', \%opts);
my $gen = $opts{G} // 0;
my $force = $opts{F} // 0;

my %validops = (
	BEGIN => {
		rank => 0,
		nargs => 1,
	},
	CONVERT => {
		rank => 1,
		nargs => 2,
	},
	TYPE => {
		rank => 2,
		nargs => 1,
	},
	ENDTYPE => {
		rank => 3,
		nargs => 0,
	},
	INSERT => {
		rank => 4,
		nargs => 1,
	},
	DEP => {
		rank => 5,
		nargs => 2,
	},
        FIELD => {
		rank => 6,
		nargs => 3,
	},
        BITFIELD => {
		rank => 6,
		nargs => 3,
	},
        ARRAY => {
		rank => 6,
		nargs => 3,
	},
	END => {
		rank => 10,
		nargs => 1,
	},
);

sub loccmp
{
	my ($a, $b) = @_;

	return ($a->{file} cmp $b->{file}
	    or $a->{line} <=> $b->{line}
	    or $a->{col} <=> $b->{col});
}

sub _opcmp
{
	my ($a, $b) = @_;
	my $ret = ($a->{loc}->{file} cmp $b->{loc}->{file}
	    or $a->{loc}->{line} <=> $b->{loc}->{line}
	    or $a->{loc}->{col} <=> $b->{loc}->{col}
	    or $validops{$a->{op}}->{rank} <=> $validops{$b->{op}}->{rank});

	return $ret if $ret;

	for (my $i = 0; $i < $a->{nargs}; $i++) {
		$ret = $a->{args}->[$i] cmp $b->{args}->[$i];
		return $ret if $ret;
	}

	return 0;
}

sub opcmp
{
	return _opcmp($a, $b);
}

sub sort_ops_unique
{
	my @tmp = sort opcmp @_;
	my $last = undef;
	my @ret = ();
	foreach my $x (@tmp) {
		next if (defined($last) and _opcmp($last, $x) == 0);
		push @ret, $x;
		$last = $x;
	}
	return @ret;
}

sub parse_loc
{
	my ($locstr) = @_;

	my @elems = split /:/, $locstr;
	die "Bad loc: $locstr" unless scalar @elems == 3;
	my $file = shift @elems;
	die "Bad file: $file" unless -r $file;
	my ($line, $col) = @elems;
	die "Bad line: $line" unless ($line + 0 == $line);
	die "Bad line: $col" unless ($col + 0 == $col);

	return {
		file => $file,
		line => $line - 1,
		col => $col - 1
	};
}

sub fmt_loc
{
	my ($loc) = @_;

	return sprintf("%s:%d:%d", $loc->{file}, $loc->{line}, $loc->{col});
}

sub uapi_unsafe
{
	my ($struct) = @_;

	return 1 if ($struct =~ m{^#}m);
	return 1 if ($struct =~ m{__SIZEOF_POINTER__});
	return 1 if ($struct =~ m{__SIZEOF_LONG__});

	return 0;
}

sub preprocess
{
	my @file = @_;
	my $skip = 0;

	foreach my $l (@file) {
		if (!$skip) {
			$skip = 1 if ($l =~ m{^\#define\s});
		}
		if ($skip) {
			$skip = 0 unless ($l =~ m{\\$}m);
			$l = "";
		}
	}

	my $n = 0;
	# Note: Handling preprocessing here is only safe for conditions
	# that do not change when compiling a compat kernel.
	my %conds = (
		__KERNEL__ => 1,
		__cplusplus => 0,
	);
	for (my $i = $n; $i <= $#file; $i = $n) {
		$n = $i + 1;
		next unless ($file[$i] =~ m{^\#if(n?)def\s+(\w+)\s*$});
		my $neg = ($1 eq "n");
		next unless exists($conds{$2});
		my $istrue = ($conds{$2}) ? !$neg : $neg;
		my $elseidx = undef;
		my $endidx = undef;
		my $j = $i+1;
		while ($j <= $#file) {
			if ($file[$j] =~ m{^\#endif\s*$}) {
				$endidx = $j;
				last;
			}
			if ($file[$j] =~ m{^\#else\s*$}) {
				last if defined($elseidx);
				$elseidx = $j++;
				next;
			}
			last if ($file[$j] =~ m{\\});
			last if ($file[$j] =~ m{\#});
			$j++;
		}
		next unless defined($endidx);
		$elseidx //= ($istrue ? $endidx : $i);
		$n = $endidx+1;
		my $s = $istrue ? ($elseidx + 1) : ($i + 1);
		my $e = $istrue ? ($endidx - 1) : ($elseidx - 1);
		while ($s <= $e) {
			$file[$s++] = "";
		}
		$file[$i] = "";
		$file[$elseidx] = "";
		$file[$endidx] = "";
	}

	return @file;
}

sub
gen_convert_helper
{
	my ($t, $typet, $fromcompat, $inline) = @_;

	return "" unless exists($t->{conv});
	my @c = split /\s+/, $t->{conv};
	die "Empty conversion list" unless scalar @c;

	my $backwards = ($inline and $fromcompat);
	@c = reverse @c if ($backwards);

	my $tag = $t->{tag};
	$tag .= " " unless $tag eq "";
	my $n = $t->{name};

	my $pfx;
	my $src;
	my $dst;
	my $srct;
	my $dstt;
	if ($fromcompat) {
		$pfx = "from";
		$dst = "native";
		$src = "compat";
		$dstt = "${tag}${n}";
		$srct = "${tag}__c${typet}_${n}";
	} else {
		$pfx = "to";
		$dst = "compat";
		$src = "native";
		$dstt = "${tag}__c${typet}_${n}";
		$srct = "${tag}${n}";
	}

	my $header;
	if ($inline) {
		$header = <<"EOF";
static __always_inline __maybe_unused void
__${pfx}_c${typet}_${n}\(${tag}${n} *p\)
\{
	union {
		${dstt} ${dst};
		const ${srct} ${src};
	} *u = (void *)p;
EOF
	} else {
		$header = <<"EOF";
static __always_inline __maybe_unused void
__${pfx}_c${typet}_${n}_2\(${dstt} *${dst}, const ${srct} *${src}\)
\{
EOF
	}

	if ($inline) {
		$src = "u->${src}.";
		$dst = "u->${dst}.";
	} else {
		$src = "${src}->";
		$dst = "${dst}->";
	}

	my $vars = "";
	my $trailer = "\}\n";
	my $fields = "\n";

	my $gen_array = sub {
		my ($fn, $arr) = @_;

		$vars = "\tunsigned long i;\n";
		$fields .= <<"EOF";
	BUILD_BUG_ON(ARRAY_SIZE(${src}${fn}) != ARRAY_SIZE(${dst}${fn}));
EOF
		if ($backwards) {
			$fields .= <<"EOF";
	for (i = 0; i < ARRAY_SIZE(${dst}${fn}); ++i)
EOF
		} else {
			$fields .= <<"EOF";
	for (i = ARRAY_SIZE(${dst}${fn}); i--; )
EOF
		}
		$fields .= "\t";
	};

	my $gen_memcpy = sub {
		my ($fn, $arr) = @_;

		my $cpy = ($inline ? "memmove" : "memcpy");
		$fields .= <<"EOF";
	BUILD_BUG_ON(sizeof(${src}${fn}) != sizeof(${dst}${fn}));
	${cpy}(&${dst}${fn}, &${src}${fn}, sizeof(${dst}${fn}));
EOF
	};

	my $gen_assign = sub {
		my ($fn, $arr) = @_;

		$fields .= <<EOF;
	${dst}${fn}${arr} = ${src}${fn}${arr};
EOF
	};

	for my $fn (@c) {
		die "Missing field: ${tag}${n}\->${fn}\n"
		    unless exists($t->{fields}->{$fn});
		my $f = $t->{fields}->{$fn};
		if ($f->{name} =~ m{\[}) {
			print "CANNOT convert nested array: "
			    . "${tag}${n}\->$fn\n";
			return "";
		}
		my $c = $f->{conversion};
		my $arr = $f->{array} ? "[i]" : "";
		if ($c eq "Memcopy") {
			&{$gen_memcpy}($fn);
			next;
		}
		if ($c eq "Copy" or ($c eq "ULong" and $typet eq "64")) {
			if ($f->{array}) {
				&{$gen_memcpy}($fn);
			} else {
				&{$gen_assign}($fn, $arr);
			}
			next;
		}
		# FIXME: Sign extenstion vs. zero extension for compat32
		if ($c eq "ULong" and ($typet eq "32")) {
			&{$gen_array}($fn) if ($f->{array});
			&{$gen_assign}($fn, $arr);
			next;
		}
		if ($c eq "UPtr64") {
			&{$gen_array}($fn) if ($f->{array});
			if ($fromcompat) {
				$fields .= <<"EOF";
	${dst}${fn}${arr} = (user_uintptr_t)compat_ptr(${src}${fn}${arr});
EOF
			} else {
				$fields .= <<"EOF";
	${dst}${fn}${arr} = (__c${typet}_ptr64 __force)${src}${fn}${arr};
EOF
			}
			next;
		}
		if ($c eq "UPtr") {
			&{$gen_array}($fn) if ($f->{array});
			if ($fromcompat) {
				$fields .= <<"EOF";
	${dst}${fn}${arr} = (user_uintptr_t)compat_ptr(${src}${fn}${arr});
EOF
			} else {
			$fields .= <<"EOF";
	${dst}${fn}${arr} = (__c${typet}_uptr __force)${src}${fn}${arr};
EOF
			}
			next;
		}
		if ($c eq "Ptr") {
			&{$gen_array}($fn) if ($f->{array});
			if ($fromcompat) {
				$fields .= <<"EOF";
	${dst}${fn}${arr} =  compat_ptr(${src}${fn}${arr});
EOF
			} else {
				$fields .= <<"EOF";
	${dst}${fn}${arr} =  (__c${typet}_uptr __force)(user_uintptr_t)${src}${fn}${arr};
EOF
			}
			next;
		}
		die "Invalid conversion($c): ${tag}${n}\->$fn\n";
	}

	return $header . $vars . $fields . $trailer;
}

sub
gen_convert
{
	my ($types, $name, $typet) = @_;

	die "No record?" unless defined($name);
	my $t = $types->{$name};
	return "" unless exists($t->{conv});

	return gen_convert_helper($t, $typet, 1, 1)
	    . gen_convert_helper($t, $typet, 0, 1)
	    . gen_convert_helper($t, $typet, 1, 0)
	    . gen_convert_helper($t, $typet, 0, 0);
}

sub
process_ops
{
	my ($ops) = @_;
	my $filename = "";
	my $outfile = "";
	my $manualfile = "";
	my @file = ();
	my @stack = ();
	my $skiptype = 0;
	my $cur;
	my %includes;
	my $body;
	my $manual;
	my $struct;
	my %allincs = ();
	my %alltypes = ();
	my %allfields = ();
	my $recordname;

	return unless scalar @{$ops};

	my $typet = ($ops->[0]->{type} == 32) ? "32" : "64";

	my $validate = sub {
		my $l = $file[$cur->{line}];
		die "Line out of range: " . fmt_loc($cur) unless defined($l);
		die "Col out of range: " . fmt_loc($cur)
		    unless ($cur->{col} <= length($l));
	};
	my $advance = sub {
		my ($by) = @_;

		&{$validate}();
		my $m = length($file[$cur->{line}]);
		$cur->{col} += $by;
		die "Col out of range: " . fmt_loc($cur) if ($cur->{col} >= $m);
		if ($cur->{col} == $m) {
			$cur->{line}++;
			$cur->{col} = 0;
		}
	};
	my $tonl = sub {
		&{$validate}();
		$cur->{line}++;
		$cur->{col} = 0;
	};
	my $findcolon = sub {
		my $done = 0;
		while (!$done) {
			my $l = substr($file[$cur->{line}], $cur->{col});
			my $i = index($l, ";");
			if ($i >= 0) {
				$struct .= substr($l, 0, $i+1);
				$struct .= "\n\n";
				&{$advance}($i+1);
				$done = 1;
			} else {
				$struct .= $l;
				&{$tonl}();
			}
		}
		$struct =~ s/__PACKED_IF_NOT_CHERI/__attribute__((packed))/g;
		$struct =~ s/\s*__CHERI_POINTER_ALIGN//g;
	};
	my $finish = sub {
		return if ($filename eq "");
		die "Bad nesting at end of file: ${filename}" unless scalar @stack == 0;
		die "Bad nesting at end of file: ${filename}" if ($skiptype);
		(my $uinc = $filename) =~ s{^.*/uapi/}{uapi/}
		    or die "Bad file name: ${filename}";
		$allincs{$uinc} = 1;
		(my $manualh = $manualfile) =~ s{^.*/uapi/}{}
		    or die "Bad file name: ${filename}";
		open(my $fh, ">", $outfile) or die "Cannot write output: $outfile ($filename): $!";
		print $fh "#pragma once\n\n";
		my @incs = sort keys %includes;
		print $fh "\n#include <linux/compat.h>\n";
		print $fh @incs if (scalar @incs);
		print $fh "#include <${manualh}>\n" if ($manual ne "");
		print $fh "\n\n";
		print $fh $body;
		close($fh);
		if ($manual ne "" and ($force or not -e $manualfile)) {
			open(my $mh, ">", $manualfile);
			print $mh "#pragma once\n\n";
			print $mh "\n";
			print $mh $manual;
			close($mh);
		}
	};
	my $addtype = sub {
		my ($name) = @_;
		return if (exists($alltypes{$name}));
		my @n = split/\s+/, $name;
		unshift @n, "" if scalar @n == 1;
		die "Strange struct name: ${name}" unless scalar(@n) == 2;
		$alltypes{$name} = {
			fullname => $name,
			tag => $n[0],
			name => $n[1],
		};
	};

	# Process fields first because they may be out of line in
	# case of nested structs
	for my $op (@{$ops}) {
		if ($op->{op} eq "FIELD" or $op->{op} eq "ARRAY"
		    or $op->{op} eq "BITFIELD")
		{
			&{$addtype}($op->{args}->[0]);
			my $f = $alltypes{$op->{args}->[0]};
			$f->{fields}->{$op->{args}->[1]} = {
				name => $op->{args}->[1],
				conversion => $op->{args}->[2],
				array => ($op->{op} eq "ARRAY"),
				bitfield => ($op->{op} eq "BITFIELD"),
			};
		}
	}
	for my $op (@{$ops}) {
		if ($op->{loc}->{file} ne $filename) {
			&{$finish}();
			$filename = $op->{loc}->{file};
			my $prefix = ($op->{type} == 32) ? "compat32_" : "compat64_";
			($outfile = $filename) =~ s{/([^/]+)$}{/${prefix}$1} or
			    die "Bad file name: ${filename}";
			($manualfile = $filename) =~ s{/([^/]+)$}{/${prefix}i_$1} or
			    die "Bad file name: ${filename}";
			open(my $fh, "<", $filename) || die "No such file: ${filename}: $!";
			@file = <$fh>;
			close($fh);
			$cur = $op->{loc};
			%includes = ();
			$body = "";
			$manual = "";
			@file = preprocess(@file);
		}
		my $oloc = $op->{loc};
                if (loccmp($cur, $oloc) > 0) {
			printf("CUR: %s %d %d\n", $cur->{file}, $cur->{line},
			    $cur->{col});
			printf("OP:  %s %d %d\n", $oloc->{file}, $oloc->{line},
			    $oloc->{col});
                }
		die "Current location beyond next op"
		    unless (loccmp($cur, $oloc) <= 0);
		my $printing = ((scalar @stack) and !$skiptype);
		while ($cur->{line} < $oloc->{line}) {
			if ($printing) {
				$struct .= substr($file[$cur->{line}], $cur->{col});
			}
			&{$tonl}();
		}
		my $cnt = $oloc->{col} - $cur->{col};
		if ($cnt > 0) {
			$struct .= substr($file[$cur->{line}], $cur->{col}, $cnt)
			    if ($printing);
			&{$advance}($cnt);
		}
		if ($op->{op} eq "BEGIN") {
			die "Bad nesting: ${filename}" if ($skiptype);
			$struct = "" if (scalar @stack == 0);
			$recordname = $op->{args}->[0];
			my @n = split/\s+/, $recordname;
			unshift @n, "" if scalar @n == 1;
			die "Strange struct name: ${recordname}"
			    unless scalar(@n) == 2;
			&{$addtype}($recordname);
			push @stack, $op;
		}
		if ($op->{op} eq "FIELD" or $op->{op} eq "ARRAY"
		    or $op->{op} eq "BITFIELD")
		{
			&{$addtype}($op->{args}->[0]);
			my $f = $alltypes{$op->{args}->[0]};
			$f->{fields}->{$op->{args}->[1]} = {
				name => $op->{args}->[1],
				conversion => $op->{args}->[2],
				array => ($op->{op} eq "ARRAY"),
				bitfield => ($op->{op} eq "BITFIELD"),
			};
		}
		if ($op->{op} eq "CONVERT") {
			&{$addtype}($op->{args}->[0]);
			my $t = $alltypes{$op->{args}->[0]};
			my $c = $op->{args}->[1];
			$t->{conv} //= $c;
			die "Mismatched conversion list" unless $t->{conv} eq $c;
		}
		if ($op->{op} eq "INSERT") {
			die "Bad nesting: ${filename}" unless scalar @stack;
			die "Bad nesting: ${filename}" if ($skiptype);
			$struct .= $op->{args}->[0];
		}
		if ($op->{op} eq "DEP") {
			die "Bad nesting: ${filename}" unless scalar @stack;
			die "Bad nesting: ${filename}" if ($skiptype);
			die "Strange dependency"
			    unless (${filename} eq $op->{args}->[0]);
			my $include = $op->{args}->[1];
			$include =~ s{^.*/uapi/}{} or
			    die "Bad include in ${filename}: ${include}";
			my $prefix = ($op->{type} == 32) ? "compat32_" : "compat64_";
			$include =~ s{/([^/]+)$}{/${prefix}$1} or
			    die "Bad include in ${filename}: ${include}";
			$includes{"#include <${include}>\n"} = 1;
		}
		if ($op->{op} eq "TYPE") {
			die "Bad nesting: ${filename}" unless scalar @stack;
			die "Bad nesting: ${filename}" if ($skiptype);
			$struct .= $op->{args}->[0];
			$skiptype = 1;
		}
		if ($op->{op} eq "ENDTYPE") {
			die "Bad nesting: ${filename}" unless scalar @stack;
			die "Bad nesting: ${filename}" unless ($skiptype);
			$skiptype = 0;
			&{$advance}(1);
			&{$validate}();
			$struct .= " " unless (substr($file[$cur->{line}], $cur->{col}, 1) =~ m{\s});
		}
		if ($op->{op} eq "END") {
			die "Bad nesting: ${filename}" if scalar @stack == 0;
			die "Bad nesting: ${filename}" if ($skiptype);
			my $loc = $stack[$#stack]->{loc};
			my @back = ();
			while (1) {
				my $tail = pop @stack;
				die "Bad nesting: ${filename}" unless (defined($tail)
				    and loccmp($tail->{loc}, $loc) == 0);
				last if ($tail->{args}->[0] eq $op->{args}->[0]);
				push @back, $tail;
			}
			push @stack, @back;
			if (scalar @stack == 0) {
				&{$findcolon}();
				if (uapi_unsafe($struct)) {
					$manual .= $struct;
				} else {
					$body .= $struct;
					$body .= gen_convert(\%alltypes,
					    $recordname, $typet);
				}
				$struct = undef;
			}
		}
	}
	&{$finish}();

	return unless $gen;

	open(my $fh, ">", "compat/includes${typet}.h") or
	    die "Cannot write to file: $!";
	open(my $cfh, ">", "compat/includes_compat${typet}.h") or
	    die "Cannot write to file: $!";
	for my $inc (sort keys %allincs) {
		printf $fh "#include <%s>\n", $inc;
		$inc =~ s{/([^/]*)$}{/compat${typet}_$1} or
		    die "Cannot make compat include name for ${inc}";
		printf $cfh "#include <%s>\n", $inc;
	}
	close($fh);
	close($cfh);

	open(my $sfh, ">", "compat/structs${typet}.h") or
	    die "Cannot write to file: $!";

	printf $sfh "#ifndef RECORD\n";
	printf $sfh "#define RECORD(TAG, T)\n";
	printf $sfh "#endif\n\n";

	printf $sfh "#ifndef FIELD\n";
	printf $sfh "#define FIELD(TAG, T, F, F2, C)\n";
	printf $sfh "#endif\n\n";

	printf $sfh "#ifndef BITFIELD\n";
	printf $sfh "#define BITFIELD(TAG, T, F, F2, C) FIELD(TAG, T, F, F2, C)\n";
	printf $sfh "#endif\n\n";

	printf $sfh "#ifndef ARRAY\n";
	printf $sfh "#define ARRAY(TAG, T, F, F2, C) FIELD(TAG, T, F, F2, C)\n";
	printf $sfh "#endif\n\n";

	for my $k (sort keys %alltypes) {
		my $v = $alltypes{$k};
		printf $sfh "RECORD(%s, %s)\n", $v->{tag}, $v->{name};
		for my $fk (sort keys %{$v->{fields}}) {
			my $fv = $v->{fields}->{$fk};
			(my $f2 = $fv->{name}) =~ s{[\s.\[\]]}{_}g;
			printf $sfh "\t%s(%s, %s, %s, %s, %s)\n",
			    $fv->{array} ? "ARRAY" : ($fv->{bitfield} ? "BITFIELD" : "FIELD"),
			    $v->{tag}, $v->{name},
			    $fv->{name}, $f2, $fv->{conversion};
		}
	}
	printf $sfh "\n#undef RECORD\n";
	close($fh);
}

while (<>) {
	chomp;
	next unless m{__C[0-9][0-9]:};
	die "Bad line: $_" unless m{(\S+):\s*warning:\s*__C(\d+):([A-Z]+)\s*(.*)};
	my ($locstr, $t, $opname, $args) = ($1, $2, $3, $4);
	die "Bad type" unless ($t == 32) or ($t eq 64);
	die "Bad op: $opname" unless (exists($validops{$opname}));
	my $loc = parse_loc($locstr);
	my $op = {
		loc => $loc,
		type => $t,
		op => $opname,
		nargs => $validops{$opname}->{nargs},
		args => []
	};
	for (my $i = 0; $i < $op->{nargs}; ++$i) {
		$args =~ s{^\s*>>([^><]*)<<\s*}{} or die "Bad arg: $args";
		push @{$op->{args}}, $1;
	}
	die "Chunk at end of args: $args" unless $args =~ m{\s*^\[};
	if ($op->{type} == 32) {
		push @ops32, $op;
	} else {
		push @ops64, $op;
	}
};

@ops32 = sort_ops_unique(@ops32);
@ops64 = sort_ops_unique(@ops64);

print "VALIDATE 32\n";
process_ops(\@ops32);
print "VALIDATE 64\n";
process_ops(\@ops64);
print "VALIDATE END\n";
print "NOPS: ", scalar @ops32, " ", scalar @ops64, "\n";
