#include <uapi/asm-generic/compat64_siginfo.h>
#include <uapi/asm-generic/compat64_signal.h>
#include <uapi/asm/compat64_bpf_perf_event.h>
#include <uapi/asm/compat64_ptrace.h>
#include <uapi/asm/compat64_sigcontext.h>
#include <uapi/asm/compat64_ucontext.h>
#include <uapi/drm/compat64_amdgpu_drm.h>
#include <uapi/drm/compat64_drm.h>
#include <uapi/drm/compat64_drm_mode.h>
#include <uapi/drm/compat64_etnaviv_drm.h>
#include <uapi/drm/compat64_exynos_drm.h>
#include <uapi/drm/compat64_lima_drm.h>
#include <uapi/drm/compat64_msm_drm.h>
#include <uapi/drm/compat64_panfrost_drm.h>
#include <uapi/drm/compat64_panthor_drm.h>
#include <uapi/drm/compat64_qaic_accel.h>
#include <uapi/drm/compat64_qxl_drm.h>
#include <uapi/drm/compat64_radeon_drm.h>
#include <uapi/drm/compat64_tegra_drm.h>
#include <uapi/drm/compat64_v3d_drm.h>
#include <uapi/drm/compat64_vc4_drm.h>
#include <uapi/drm/compat64_virtgpu_drm.h>
#include <uapi/drm/compat64_xe_drm.h>
#include <uapi/linux/compat64_aio_abi.h>
#include <uapi/linux/compat64_atm.h>
#include <uapi/linux/compat64_atm_tcp.h>
#include <uapi/linux/compat64_atmapi.h>
#include <uapi/linux/compat64_atmdev.h>
#include <uapi/linux/compat64_atmsap.h>
#include <uapi/linux/compat64_atmsvc.h>
#include <uapi/linux/compat64_blk-crypto.h>
#include <uapi/linux/compat64_blkpg.h>
#include <uapi/linux/compat64_bpf.h>
#include <uapi/linux/compat64_bsg.h>
#include <uapi/linux/compat64_btrfs.h>
#include <uapi/linux/compat64_cciss_defs.h>
#include <uapi/linux/compat64_cciss_ioctl.h>
#include <uapi/linux/compat64_cdrom.h>
#include <uapi/linux/compat64_chio.h>
#include <uapi/linux/compat64_coda.h>
#include <uapi/linux/compat64_comedi.h>
#include <uapi/linux/compat64_cxl_mem.h>
#include <uapi/linux/compat64_dlm.h>
#include <uapi/linux/compat64_dlm_device.h>
#include <uapi/linux/dvb/compat64_frontend.h>
#include <uapi/linux/dvb/compat64_osd.h>
#include <uapi/linux/dvb/compat64_video.h>
#include <uapi/linux/compat64_ethtool.h>
#include <uapi/linux/compat64_eventpoll.h>
#include <uapi/linux/compat64_fb.h>
#include <uapi/linux/compat64_fd.h>
#include <uapi/linux/compat64_filter.h>
#include <uapi/linux/compat64_firewire-cdev.h>
#include <uapi/linux/compat64_fs.h>
#include <uapi/linux/compat64_fsverity.h>
#include <uapi/linux/compat64_futex.h>
#include <uapi/linux/compat64_hdreg.h>
#include <uapi/linux/compat64_i2c-dev.h>
#include <uapi/linux/compat64_i2c.h>
#include <uapi/linux/compat64_if.h>
#include <uapi/linux/compat64_if_pppol2tp.h>
#include <uapi/linux/compat64_if_pppox.h>
#include <uapi/linux/compat64_in.h>
#include <uapi/linux/compat64_in6.h>
#include <uapi/linux/compat64_input.h>
#include <uapi/linux/compat64_io_uring.h>
#include <uapi/linux/io_uring/compat64_query.h>
#include <uapi/linux/compat64_iommufd.h>
#include <uapi/linux/compat64_ipc.h>
#include <uapi/linux/compat64_ipmi.h>
#include <uapi/linux/compat64_ivtv.h>
#include <uapi/linux/compat64_ivtvfb.h>
#include <uapi/linux/compat64_kd.h>
#include <uapi/linux/compat64_keyctl.h>
#include <uapi/linux/compat64_l2tp.h>
#include <uapi/linux/compat64_media.h>
#include <uapi/linux/mmc/compat64_ioctl.h>
#include <uapi/linux/compat64_mptcp.h>
#include <uapi/linux/compat64_msg.h>
#include <uapi/linux/compat64_netfilter.h>
#include <uapi/linux/netfilter/compat64_x_tables.h>
#include <uapi/linux/netfilter/compat64_xt_CT.h>
#include <uapi/linux/netfilter/compat64_xt_IDLETIMER.h>
#include <uapi/linux/netfilter/compat64_xt_LED.h>
#include <uapi/linux/netfilter/compat64_xt_RATEEST.h>
#include <uapi/linux/netfilter/compat64_xt_TEE.h>
#include <uapi/linux/netfilter/compat64_xt_bpf.h>
#include <uapi/linux/netfilter/compat64_xt_cgroup.h>
#include <uapi/linux/netfilter/compat64_xt_connlimit.h>
#include <uapi/linux/netfilter/compat64_xt_hashlimit.h>
#include <uapi/linux/netfilter/compat64_xt_limit.h>
#include <uapi/linux/netfilter/compat64_xt_nfacct.h>
#include <uapi/linux/netfilter/compat64_xt_quota.h>
#include <uapi/linux/netfilter/compat64_xt_rateest.h>
#include <uapi/linux/netfilter/compat64_xt_statistic.h>
#include <uapi/linux/netfilter/compat64_xt_string.h>
#include <uapi/linux/netfilter_arp/compat64_arp_tables.h>
#include <uapi/linux/netfilter_bridge/compat64_ebtables.h>
#include <uapi/linux/netfilter_ipv4/compat64_ip_tables.h>
#include <uapi/linux/netfilter_ipv6/compat64_ip6_tables.h>
#include <uapi/linux/compat64_nfs2.h>
#include <uapi/linux/compat64_nfs3.h>
#include <uapi/linux/compat64_nfs4_mount.h>
#include <uapi/linux/compat64_nfs_mount.h>
#include <uapi/linux/compat64_nsm.h>
#include <uapi/linux/compat64_nvme_ioctl.h>
#include <uapi/linux/compat64_omap3isp.h>
#include <uapi/linux/compat64_omapfb.h>
#include <uapi/linux/compat64_phonet.h>
#include <uapi/linux/compat64_ppp-ioctl.h>
#include <uapi/linux/compat64_prctl.h>
#include <uapi/linux/compat64_ptrace.h>
#include <uapi/linux/raid/compat64_md_p.h>
#include <uapi/linux/compat64_rio_cm_cdev.h>
#include <uapi/linux/compat64_rio_mport_cdev.h>
#include <uapi/linux/compat64_rkisp1-config.h>
#include <uapi/linux/compat64_route.h>
#include <uapi/linux/compat64_rseq.h>
#include <uapi/linux/compat64_rxrpc.h>
#include <uapi/linux/compat64_sched.h>
#include <uapi/linux/compat64_sctp.h>
#include <uapi/linux/compat64_sed-opal.h>
#include <uapi/linux/compat64_sem.h>
#include <uapi/linux/compat64_shm.h>
#include <uapi/linux/compat64_soundcard.h>
#include <uapi/linux/spi/compat64_spidev.h>
#include <uapi/linux/compat64_sync_file.h>
#include <uapi/linux/compat64_sysctl.h>
#include <uapi/linux/compat64_tcp.h>
#include <uapi/linux/compat64_tee.h>
#include <uapi/linux/compat64_time_types.h>
#include <uapi/linux/compat64_tipc_config.h>
#include <uapi/linux/compat64_ublk_cmd.h>
#include <uapi/linux/compat64_uinput.h>
#include <uapi/linux/compat64_uio.h>
#include <uapi/linux/usb/compat64_tmc.h>
#include <uapi/linux/compat64_usbdevice_fs.h>
#include <uapi/linux/compat64_uvcvideo.h>
#include <uapi/linux/compat64_v4l2-common.h>
#include <uapi/linux/compat64_v4l2-subdev.h>
#include <uapi/linux/compat64_vfio.h>
#include <uapi/linux/compat64_videodev2.h>
#include <uapi/linux/compat64_virtio_ring.h>
#include <uapi/linux/compat64_vm_sockets.h>
#include <uapi/linux/compat64_wireless.h>
#include <uapi/linux/compat64_xattr.h>
#include <uapi/misc/compat64_xilinx_sdfec.h>
#include <uapi/mtd/compat64_mtd-abi.h>
#include <uapi/sound/compat64_asequencer.h>
#include <uapi/sound/compat64_asound.h>
#include <uapi/sound/compat64_hdsp.h>
#include <uapi/sound/compat64_hdspm.h>
