#include <uapi/asm-generic/siginfo.h>
#include <uapi/asm-generic/signal.h>
#include <uapi/asm/bpf_perf_event.h>
#include <uapi/asm/elf.h>
#include <uapi/asm/ptrace.h>
#include <uapi/asm/sigcontext.h>
#include <uapi/asm/ucontext.h>
#include <uapi/drm/amdgpu_drm.h>
#include <uapi/drm/drm.h>
#include <uapi/drm/drm_mode.h>
#include <uapi/drm/etnaviv_drm.h>
#include <uapi/drm/exynos_drm.h>
#include <uapi/drm/lima_drm.h>
#include <uapi/drm/msm_drm.h>
#include <uapi/drm/panfrost_drm.h>
#include <uapi/drm/panthor_drm.h>
#include <uapi/drm/qaic_accel.h>
#include <uapi/drm/qxl_drm.h>
#include <uapi/drm/radeon_drm.h>
#include <uapi/drm/tegra_drm.h>
#include <uapi/drm/v3d_drm.h>
#include <uapi/drm/vc4_drm.h>
#include <uapi/drm/virtgpu_drm.h>
#include <uapi/drm/xe_drm.h>
#include <uapi/linux/aio_abi.h>
#include <uapi/linux/atm.h>
#include <uapi/linux/atm_tcp.h>
#include <uapi/linux/atmapi.h>
#include <uapi/linux/atmdev.h>
#include <uapi/linux/atmsap.h>
#include <uapi/linux/atmsvc.h>
#include <uapi/linux/blk-crypto.h>
#include <uapi/linux/blkpg.h>
#include <uapi/linux/bpf.h>
#include <uapi/linux/bsg.h>
#include <uapi/linux/btrfs.h>
#include <uapi/linux/cciss_defs.h>
#include <uapi/linux/cciss_ioctl.h>
#include <uapi/linux/cdrom.h>
#include <uapi/linux/chio.h>
#include <uapi/linux/coda.h>
#include <uapi/linux/comedi.h>
#include <uapi/linux/cxl_mem.h>
#include <uapi/linux/dlm.h>
#include <uapi/linux/dlm_device.h>
#include <uapi/linux/dvb/frontend.h>
#include <uapi/linux/dvb/osd.h>
#include <uapi/linux/dvb/video.h>
#include <uapi/linux/ethtool.h>
#include <uapi/linux/eventpoll.h>
#include <uapi/linux/fb.h>
#include <uapi/linux/fd.h>
#include <uapi/linux/filter.h>
#include <uapi/linux/firewire-cdev.h>
#include <uapi/linux/fs.h>
#include <uapi/linux/fsverity.h>
#include <uapi/linux/futex.h>
#include <uapi/linux/hdreg.h>
#include <uapi/linux/i2c-dev.h>
#include <uapi/linux/i2c.h>
#include <uapi/linux/if.h>
#include <uapi/linux/if_pppol2tp.h>
#include <uapi/linux/if_pppox.h>
#include <uapi/linux/in.h>
#include <uapi/linux/in6.h>
#include <uapi/linux/input.h>
#include <uapi/linux/io_uring.h>
#include <uapi/linux/io_uring/query.h>
#include <uapi/linux/iommufd.h>
#include <uapi/linux/ipc.h>
#include <uapi/linux/ipmi.h>
#include <uapi/linux/ivtv.h>
#include <uapi/linux/ivtvfb.h>
#include <uapi/linux/kd.h>
#include <uapi/linux/keyctl.h>
#include <uapi/linux/l2tp.h>
#include <uapi/linux/media.h>
#include <uapi/linux/mmc/ioctl.h>
#include <uapi/linux/mptcp.h>
#include <uapi/linux/msg.h>
#include <uapi/linux/netfilter.h>
#include <uapi/linux/netfilter/x_tables.h>
#include <uapi/linux/netfilter/xt_CT.h>
#include <uapi/linux/netfilter/xt_IDLETIMER.h>
#include <uapi/linux/netfilter/xt_LED.h>
#include <uapi/linux/netfilter/xt_RATEEST.h>
#include <uapi/linux/netfilter/xt_TEE.h>
#include <uapi/linux/netfilter/xt_bpf.h>
#include <uapi/linux/netfilter/xt_cgroup.h>
#include <uapi/linux/netfilter/xt_connlimit.h>
#include <uapi/linux/netfilter/xt_hashlimit.h>
#include <uapi/linux/netfilter/xt_limit.h>
#include <uapi/linux/netfilter/xt_nfacct.h>
#include <uapi/linux/netfilter/xt_quota.h>
#include <uapi/linux/netfilter/xt_rateest.h>
#include <uapi/linux/netfilter/xt_statistic.h>
#include <uapi/linux/netfilter/xt_string.h>
#include <uapi/linux/netfilter_arp/arp_tables.h>
#include <uapi/linux/netfilter_bridge/ebtables.h>
#include <uapi/linux/netfilter_ipv4/ip_tables.h>
#include <uapi/linux/netfilter_ipv6/ip6_tables.h>
#include <uapi/linux/nfs2.h>
#include <uapi/linux/nfs3.h>
#include <uapi/linux/nfs4_mount.h>
#include <uapi/linux/nfs_mount.h>
#include <uapi/linux/nsm.h>
#include <uapi/linux/nvme_ioctl.h>
#include <uapi/linux/omap3isp.h>
#include <uapi/linux/omapfb.h>
#include <uapi/linux/phonet.h>
#include <uapi/linux/ppp-ioctl.h>
#include <uapi/linux/pr.h>
#include <uapi/linux/prctl.h>
#include <uapi/linux/ptrace.h>
#include <uapi/linux/raid/md_p.h>
#include <uapi/linux/rio_cm_cdev.h>
#include <uapi/linux/rio_mport_cdev.h>
#include <uapi/linux/rkisp1-config.h>
#include <uapi/linux/route.h>
#include <uapi/linux/rseq.h>
#include <uapi/linux/rxrpc.h>
#include <uapi/linux/sched.h>
#include <uapi/linux/sctp.h>
#include <uapi/linux/sed-opal.h>
#include <uapi/linux/sem.h>
#include <uapi/linux/shm.h>
#include <uapi/linux/soundcard.h>
#include <uapi/linux/spi/spidev.h>
#include <uapi/linux/sync_file.h>
#include <uapi/linux/sysctl.h>
#include <uapi/linux/tcp.h>
#include <uapi/linux/tee.h>
#include <uapi/linux/time_types.h>
#include <uapi/linux/tipc_config.h>
#include <uapi/linux/ublk_cmd.h>
#include <uapi/linux/uinput.h>
#include <uapi/linux/uio.h>
#include <uapi/linux/usb/tmc.h>
#include <uapi/linux/usbdevice_fs.h>
#include <uapi/linux/uvcvideo.h>
#include <uapi/linux/v4l2-common.h>
#include <uapi/linux/v4l2-subdev.h>
#include <uapi/linux/vfio.h>
#include <uapi/linux/videodev2.h>
#include <uapi/linux/virtio_ring.h>
#include <uapi/linux/vm_sockets.h>
#include <uapi/linux/wireless.h>
#include <uapi/linux/xattr.h>
#include <uapi/misc/xilinx_sdfec.h>
#include <uapi/mtd/mtd-abi.h>
#include <uapi/sound/asequencer.h>
#include <uapi/sound/asound.h>
#include <uapi/sound/hdsp.h>
#include <uapi/sound/hdspm.h>
