/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef __ASM_CHERI_H
#define __ASM_CHERI_H

#define CHERI_PERMS_READ \
	(CHERI_PERM_LOAD | CHERI_PERM_LOAD_CAP | ARM_CAP_PERMISSION_MUTABLE_LOAD)

#define CHERI_PERMS_EXEC \
	(CHERI_PERM_EXECUTE | CHERI_PERM_SYSTEM_REGS | ARM_CAP_PERMISSION_EXECUTIVE)

#endif /* __ASM_CHERI_H */
