# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_STRPERF) += strperf.o
strperf-y :=	framework.o strtest.o
strperf-y +=	strchrnul.o memchr.o memcmp.o memcpy.o memset.o stpcpy.o \
		strcmp.o strcspn.o strlen.o strncmp.o strnlen.o \
		strrchr.o strspn.o

