#ifndef __ASM_CHERIMAP_H
#define __ASM_CHERIMAP_H


/* Registers */
#define __CAPREG_ra	cra
#define __CAPREG_cra	cra
#define __CAPREG_x1	c1
#define __CAPREG_c1	c1
#define __INTREG_ra	ra
#define __INTREG_cra	ra
#define __INTREG_x1	x1
#define __INTREG_c1	x1
#define __CAPREG_sp	csp
#define __CAPREG_csp	csp
#define __CAPREG_x2	c2
#define __CAPREG_c2	c2
#define __INTREG_sp	sp
#define __INTREG_csp	sp
#define __INTREG_x2	x2
#define __INTREG_c2	x2
#define __CAPREG_gp	cgp
#define __CAPREG_cgp	cgp
#define __CAPREG_x3	c3
#define __CAPREG_c3	c3
#define __INTREG_gp	gp
#define __INTREG_cgp	gp
#define __INTREG_x3	x3
#define __INTREG_c3	x3
#define __CAPREG_tp	ctp
#define __CAPREG_ctp	ctp
#define __CAPREG_x4	c4
#define __CAPREG_c4	c4
#define __INTREG_tp	tp
#define __INTREG_ctp	tp
#define __INTREG_x4	x4
#define __INTREG_c4	x4
#define __CAPREG_t0	ct0
#define __CAPREG_ct0	ct0
#define __CAPREG_x5	c5
#define __CAPREG_c5	c5
#define __INTREG_t0	t0
#define __INTREG_ct0	t0
#define __INTREG_x5	x5
#define __INTREG_c5	x5
#define __CAPREG_t1	ct1
#define __CAPREG_ct1	ct1
#define __CAPREG_x6	c6
#define __CAPREG_c6	c6
#define __INTREG_t1	t1
#define __INTREG_ct1	t1
#define __INTREG_x6	x6
#define __INTREG_c6	x6
#define __CAPREG_t2	ct2
#define __CAPREG_ct2	ct2
#define __CAPREG_x7	c7
#define __CAPREG_c7	c7
#define __INTREG_t2	t2
#define __INTREG_ct2	t2
#define __INTREG_x7	x7
#define __INTREG_c7	x7
#define __CAPREG_s0	cs0
#define __CAPREG_cs0	cs0
#define __CAPREG_x8	c8
#define __CAPREG_c8	c8
#define __INTREG_s0	s0
#define __INTREG_cs0	s0
#define __INTREG_x8	x8
#define __INTREG_c8	x8
#define __CAPREG_s1	cs1
#define __CAPREG_cs1	cs1
#define __CAPREG_x9	c9
#define __CAPREG_c9	c9
#define __INTREG_s1	s1
#define __INTREG_cs1	s1
#define __INTREG_x9	x9
#define __INTREG_c9	x9
#define __CAPREG_a0	ca0
#define __CAPREG_ca0	ca0
#define __CAPREG_x10	c10
#define __CAPREG_c10	c10
#define __INTREG_a0	a0
#define __INTREG_ca0	a0
#define __INTREG_x10	x10
#define __INTREG_c10	x10
#define __CAPREG_a1	ca1
#define __CAPREG_ca1	ca1
#define __CAPREG_x11	c11
#define __CAPREG_c11	c11
#define __INTREG_a1	a1
#define __INTREG_ca1	a1
#define __INTREG_x11	x11
#define __INTREG_c11	x11
#define __CAPREG_a2	ca2
#define __CAPREG_ca2	ca2
#define __CAPREG_x12	c12
#define __CAPREG_c12	c12
#define __INTREG_a2	a2
#define __INTREG_ca2	a2
#define __INTREG_x12	x12
#define __INTREG_c12	x12
#define __CAPREG_a3	ca3
#define __CAPREG_ca3	ca3
#define __CAPREG_x13	c13
#define __CAPREG_c13	c13
#define __INTREG_a3	a3
#define __INTREG_ca3	a3
#define __INTREG_x13	x13
#define __INTREG_c13	x13
#define __CAPREG_a4	ca4
#define __CAPREG_ca4	ca4
#define __CAPREG_x14	c14
#define __CAPREG_c14	c14
#define __INTREG_a4	a4
#define __INTREG_ca4	a4
#define __INTREG_x14	x14
#define __INTREG_c14	x14
#define __CAPREG_a5	ca5
#define __CAPREG_ca5	ca5
#define __CAPREG_x15	c15
#define __CAPREG_c15	c15
#define __INTREG_a5	a5
#define __INTREG_ca5	a5
#define __INTREG_x15	x15
#define __INTREG_c15	x15
#define __CAPREG_a6	ca6
#define __CAPREG_ca6	ca6
#define __CAPREG_x16	c16
#define __CAPREG_c16	c16
#define __INTREG_a6	a6
#define __INTREG_ca6	a6
#define __INTREG_x16	x16
#define __INTREG_c16	x16
#define __CAPREG_a7	ca7
#define __CAPREG_ca7	ca7
#define __CAPREG_x17	c17
#define __CAPREG_c17	c17
#define __INTREG_a7	a7
#define __INTREG_ca7	a7
#define __INTREG_x17	x17
#define __INTREG_c17	x17
#define __CAPREG_s2	cs2
#define __CAPREG_cs2	cs2
#define __CAPREG_x18	c18
#define __CAPREG_c18	c18
#define __INTREG_s2	s2
#define __INTREG_cs2	s2
#define __INTREG_x18	x18
#define __INTREG_c18	x18
#define __CAPREG_s3	cs3
#define __CAPREG_cs3	cs3
#define __CAPREG_x19	c19
#define __CAPREG_c19	c19
#define __INTREG_s3	s3
#define __INTREG_cs3	s3
#define __INTREG_x19	x19
#define __INTREG_c19	x19
#define __CAPREG_s4	cs4
#define __CAPREG_cs4	cs4
#define __CAPREG_x20	c20
#define __CAPREG_c20	c20
#define __INTREG_s4	s4
#define __INTREG_cs4	s4
#define __INTREG_x20	x20
#define __INTREG_c20	x20
#define __CAPREG_s5	cs5
#define __CAPREG_cs5	cs5
#define __CAPREG_x21	c21
#define __CAPREG_c21	c21
#define __INTREG_s5	s5
#define __INTREG_cs5	s5
#define __INTREG_x21	x21
#define __INTREG_c21	x21
#define __CAPREG_s6	cs6
#define __CAPREG_cs6	cs6
#define __CAPREG_x22	c22
#define __CAPREG_c22	c22
#define __INTREG_s6	s6
#define __INTREG_cs6	s6
#define __INTREG_x22	x22
#define __INTREG_c22	x22
#define __CAPREG_s7	cs7
#define __CAPREG_cs7	cs7
#define __CAPREG_x23	c23
#define __CAPREG_c23	c23
#define __INTREG_s7	s7
#define __INTREG_cs7	s7
#define __INTREG_x23	x23
#define __INTREG_c23	x23
#define __CAPREG_s8	cs8
#define __CAPREG_cs8	cs8
#define __CAPREG_x24	c24
#define __CAPREG_c24	c24
#define __INTREG_s8	s8
#define __INTREG_cs8	s8
#define __INTREG_x24	x24
#define __INTREG_c24	x24
#define __CAPREG_s9	cs9
#define __CAPREG_cs9	cs9
#define __CAPREG_x25	c25
#define __CAPREG_c25	c25
#define __INTREG_s9	s9
#define __INTREG_cs9	s9
#define __INTREG_x25	x25
#define __INTREG_c25	x25
#define __CAPREG_s10	cs10
#define __CAPREG_cs10	cs10
#define __CAPREG_x26	c26
#define __CAPREG_c26	c26
#define __INTREG_s10	s10
#define __INTREG_cs10	s10
#define __INTREG_x26	x26
#define __INTREG_c26	x26
#define __CAPREG_s11	cs11
#define __CAPREG_cs11	cs11
#define __CAPREG_x27	c27
#define __CAPREG_c27	c27
#define __INTREG_s11	s11
#define __INTREG_cs11	s11
#define __INTREG_x27	x27
#define __INTREG_c27	x27
#define __CAPREG_t3	ct3
#define __CAPREG_ct3	ct3
#define __CAPREG_x28	c28
#define __CAPREG_c28	c28
#define __INTREG_t3	t3
#define __INTREG_ct3	t3
#define __INTREG_x28	x28
#define __INTREG_c28	x28
#define __CAPREG_t4	ct4
#define __CAPREG_ct4	ct4
#define __CAPREG_x29	c29
#define __CAPREG_c29	c29
#define __INTREG_t4	t4
#define __INTREG_ct4	t4
#define __INTREG_x29	x29
#define __INTREG_c29	x29
#define __CAPREG_t5	ct5
#define __CAPREG_ct5	ct5
#define __CAPREG_x30	c30
#define __CAPREG_c30	c30
#define __INTREG_t5	t5
#define __INTREG_ct5	t5
#define __INTREG_x30	x30
#define __INTREG_c30	x30
#define __CAPREG_t6	ct6
#define __CAPREG_ct6	ct6
#define __CAPREG_x31	c31
#define __CAPREG_c31	c31
#define __INTREG_t6	t6
#define __INTREG_ct6	t6
#define __INTREG_x31	x31
#define __INTREG_c31	x31

/* Special registers */
#define __CAPREG_x0	cnull
#define __CAPREG_c0	cnull
#define __CAPREG_null	cnull
#define __CAPREG_cnull	cnull
#define __INTREG_x0	x0
#define __INTREG_c0	x0
#define __INTREG_null	x0
#define __INTREG_cnull	x0


/* Instructions */
#define __CAPINSN_addi	caddi
#define __CAPINSN_caddi	caddi
#define __INTINSN_addi	addi
#define __INTINSN_caddi	addi
#define __CAPINSN_la	lgc
#define __CAPINSN_lgc	lgc
#define __INTINSN_la	la
#define __INTINSN_lgc	la

#ifdef CONFIG_CHERI_KERNEL
#define __CREG(X)	__CAPREG_##X
#define __IREG(X)	__INTREG_##X
#define __CINSN(I)	__CAPINSN_##I
#define __IINSN(I)	__INTINSN_##I
#else /* CONFIG_CHERI_KERNEL */
#define __CREG(X)	X
#define __IREG(X)	X
#define __CINSN(I)	I
#define __IINSN(I)	I
#endif /* CONFIG_CHERI_KERNEL */

#ifdef __ASSEMBLY__
#define CREG(X)		__CREG(X)
#define IREG(X)		__IREG(X)
#define CINSN(I)	__CINSN(I)
#define IINSN(I)	__IINSN(I)
#else /* __ASSEMBLY__ */
#define ___TOSTR(X)	#X
#define __TOSTR(X)	___TOSTR(X)
#define CREG(X)		__TOSTR(__CREG(X))
#define IREG(X)		__TOSTR(__IREG(X))
#define CINSN(I)	__TOSTR(__CINSN(I))
#define IINSN(I)	__TOSTR(__IINSN(I))
#endif /* __ASSEMBLY__ */


#endif /* __ASM_CHERIMAP_H */
