# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_CODASIP) += a730-mp4-hobgoblin2-profpga.dtb
dtb-$(CONFIG_ARCH_CODASIP) += x730-mp4-hobgoblin2-profpga.dtb
dtb-$(CONFIG_ARCH_CODASIP) += a730-mp1-hobgoblin2-vcu118.dtb
dtb-$(CONFIG_ARCH_CODASIP) += a730-mp4-hobgoblin2-vcu118.dtb
dtb-$(CONFIG_ARCH_CODASIP) += x730-mp1-hobgoblin2-vcu118.dtb
dtb-$(CONFIG_ARCH_CODASIP) += x730-mp4-hobgoblin2-vcu118.dtb
dtb-$(CONFIG_ARCH_CODASIP) += prime.dtb
